distancias = {
    ("Bogotá", "Cali"): 460,
    ("Bogotá", "Medellín"): 415,
    ("Bogotá", "Cartagena"): 1035,
    ("Bogotá", "Barranquilla"): 980,
    ("Bogotá", "Bucaramanga"): 400,
    ("Bogotá", "Santa Marta"): 940,
    ("Bogotá", "Pereira"): 330,
    ("Bogotá", "Manizales"): 290,
    ("Bogotá", "Armenia"): 300,
    ("Bogotá", "Villavicencio"): 120,
    ("Cali", "Medellín"): 415,
    ("Cali", "Cartagena"): 1010,
    ("Cali", "Barranquilla"): 960,
    ("Cali", "Bucaramanga"): 735,
    ("Cali", "Santa Marta"): 920,
    ("Cali", "Pereira"): 220,
    ("Cali", "Manizales"): 240,
    ("Cali", "Armenia"): 180,
    ("Cali", "Villavicencio"): 500,
    ("Medellín", "Cartagena"): 630,
    ("Medellín", "Barranquilla"): 590,
    ("Medellín", "Bucaramanga"): 390,
    ("Medellín", "Santa Marta"): 670,
    ("Medellín", "Pereira"): 210,
    ("Medellín", "Manizales"): 180,
    ("Medellín", "Armenia"): 250,
    ("Medellín", "Villavicencio"): 520,
    ("Cartagena", "Barranquilla"): 115,
    ("Cartagena", "Bucaramanga"): 780,
    ("Cartagena", "Santa Marta"): 225,
    ("Cartagena", "Pereira"): 920,
    ("Cartagena", "Manizales"): 890,
    ("Cartagena", "Armenia"): 930,
    ("Cartagena", "Villavicencio"): 1040,
    ("Barranquilla", "Bucaramanga"): 670,
    ("Barranquilla", "Santa Marta"): 95,
    ("Barranquilla", "Pereira"): 910,
    ("Barranquilla", "Manizales"): 880,
    ("Barranquilla", "Armenia"): 920,
    ("Barranquilla", "Villavicencio"): 1030,
    ("Bucaramanga", "Santa Marta"): 675,
    ("Bucaramanga", "Pereira"): 520,
    ("Bucaramanga", "Manizales"): 490,
    ("Bucaramanga", "Armenia"): 530,
    ("Bucaramanga", "Villavicencio"): 380,
    ("Santa Marta", "Pereira"): 1000,
    ("Santa Marta", "Armenia"): 1010,
    ("Pereira", "Manizales"): 50,
    ("Pereira", "Armenia"): 40,
    ("Pereira", "Villavicencio"): 480,
    ("Manizales", "Armenia"): 80,
    ("Manizales", "Villavicencio"): 470,
    ("Armenia", "Villavicencio"): 460,
}
